---
# See: <https://www.gitpod.io/docs/configure/workspaces>


image: caian/gitpod-latex-workspace:latest


tasks:
  - name: Build
    command: |
      cd document
      make


vscode:
  extensions:
    - eamodio.gitlens
    - editorconfig.editorconfig
    - exiasr.hadolint
    - ms-azuretools.vscode-docker
    - ms-vscode.makefile-tools
    - redhat.vscode-yaml
