sudo: required
language: generic

services:
  - docker

stages:
  - compile

jobs:
  include:
    - stage: compile
      name: "Compile documents"
      script:
        - docker build -t compiled_docs .
