sudo: required
language: generic

services:
  - docker

stages:
  - compile

jobs:
  include:
    - stage: compile
      name: "Compile documents"
      script:
        - make build
        - make upload
      if: tag IS present
