sudo: required
language: generic

services:
  - docker

stages:
  - compile

jobs:
  include:
    - stage: compile
      name: "Compile documents"
      install:
        - pip3 install awscli --upgrade
      script:
        - make build
        - make update
      if: tag IS present
