name: build-latex-document


inputs:
  docker-image-tag:
    required: true


runs:
  using: composite
  steps:
    - name: Build image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false
        load: true
        tags: ${{ inputs.docker-image-tag }}

    - name: Build
      run: cd document && make build-docs
      shell: bash
