name: build-latex-document

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Update awscli
      run: pip3 install awscli --upgrade
      shell: bash

    - name: Build
      run: make build
      shell: bash
