name: build-latex-document
description: 'Builds the LaTeX documents using Docker'


inputs:
  docker-image-tag:
    required: true
    description: ''


runs:
  using: composite
  steps:
    - name: Build image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false
        load: true
        tags: ${{ inputs.docker-image-tag }}

    - name: Build
      run: cd document && make compile-from-image
      shell: bash
