name: build

on:
  workflow_dispatch:

  push:
    branches: master
    paths-ignore: '**.md'


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build LaTeX document
        uses: ./.github/actions/build-latex-document
