name: build


on:
  pull_request:
    branches: ['*']
    paths-ignore: ['**.md']

  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Build LaTeX document
        uses: ./.github/actions/build-latex-document
        with:
          docker-image-tag: 'compiled-docs:latest'
