name: build


on:
  pull_request:
    branches: ['*']
    paths-ignore: ['**.md']

  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Build LaTeX documents using Docker
        run: cd document && make compile-from-image
