name: upload


on:
  push:
    paths-ignore: ['**.md']
    tags: ['v[0-9]+.[0-9]+.[0-9]+']


jobs:
  upload:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3.0.1
        with:
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - uses: actions/checkout@v3

      - name: Build LaTeX documents using Docker
        run: cd document && make compile-from-image

      - name: Upload documents
        run: cd document && make upload
