name: upload


on:
  push:
    paths-ignore: ['**.md']
    tags: ['v[0-9]+.[0-9]+.[0-9]+']


jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Build LaTeX document
        uses: ./.github/actions/build-latex-document
        with:
          docker-image-tag: compiled-docs:latest

      - name: Upload documents
        run: cd document && make upload
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
